version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DB: "./server/pair.db"
    depends_on:
      - rabbitmq
      - celery

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  celery:
    build: .
    command: celery -A receiver  worker --loglevel=DEBUG
    working_dir: /code/server
    environment:
     DB: "pair.db"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq